In [1]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import glob

# Problema 1: Portifolio de Investimentos

## Dados:
 Série histórica de retornos de investimentos ao longo de 12 meses

In [2]:
"""
Análise de Risco de Portfolio de Investimentos

Use normas e desvio padrão para analisar risco e retorno de investimentos.
"""
print("\n" + "=" * 60)
print("ANÁLISE DE RISCO DE PORTFOLIO DE INVESTIMENTOS")
print("=" * 60)

# Retornos mensais (%) de 5 ativos durante 12 meses
ativos = ['Ação A', 'Ação B', 'Ação C', 'Título D', 'Fundo E']

retornos = np.array([
    [2.1, -1.5, 3.2, 0.8, 1.2],   # Mês 1
    [1.8, 2.3, -0.5, 0.9, 1.1],   # Mês 2
    [-0.5, 1.8, 2.1, 0.7, 0.9],   # Mês 3
    [3.2, -2.1, 1.8, 0.8, 1.3],   # Mês 4
    [0.9, 3.5, -1.2, 0.6, 1.0],   # Mês 5
    [2.5, 0.8, 2.8, 0.9, 1.4],    # Mês 6
    [-1.2, 2.9, 0.5, 0.7, 0.8],   # Mês 7
    [1.6, -0.8, 3.1, 0.8, 1.2],   # Mês 8
    [2.8, 1.5, -0.8, 0.6, 1.1],   # Mês 9
    [0.3, 2.7, 1.9, 0.9, 1.3],    # Mês 10
    [1.9, -1.3, 2.4, 0.7, 0.9],   # Mês 11
    [2.2, 1.1, 0.7, 0.8, 1.2]     # Mês 12
])

print("Retornos mensais (%) dos ativos:")
print(f"{'Mês':<5}", end="")
for ativo in ativos:
    print(f"{ativo:>10}", end="")
print()

for i in range(12):
    print(f"{i+1:<5}", end="")
    for j in range(5):
        print(f"{retornos[i,j]:>10.1f}", end="")
    print()



ANÁLISE DE RISCO DE PORTFOLIO DE INVESTIMENTOS
Retornos mensais (%) dos ativos:
Mês      Ação A    Ação B    Ação C  Título D   Fundo E
1           2.1      -1.5       3.2       0.8       1.2
2           1.8       2.3      -0.5       0.9       1.1
3          -0.5       1.8       2.1       0.7       0.9
4           3.2      -2.1       1.8       0.8       1.3
5           0.9       3.5      -1.2       0.6       1.0
6           2.5       0.8       2.8       0.9       1.4
7          -1.2       2.9       0.5       0.7       0.8
8           1.6      -0.8       3.1       0.8       1.2
9           2.8       1.5      -0.8       0.6       1.1
10          0.3       2.7       1.9       0.9       1.3
11          1.9      -1.3       2.4       0.7       0.9
12          2.2       1.1       0.7       0.8       1.2


In [10]:
# a) Análise de retorno e risco individual
print(f"\na) Análise individual dos ativos:")
print(f"{'Ativo':<10} {'Retorno Médio':<15} {'Risco (Std)':<12} {'Sharpe Ratio':<12}")

retornos_medios = np.mean(retornos, axis=0)
riscos = np.std(retornos, axis=0)
sharpe_ratios = retornos_medios / riscos

for i, ativo in enumerate(ativos):
    pass
    print(f"{ativo:<10} {retornos_medios[i]:<15.2f} {riscos[i]:<12.3f} {sharpe_ratios[i]:<12.3f}")


a) Análise individual dos ativos:
Ativo      Retorno Médio   Risco (Std)  Sharpe Ratio
Ação A     1.47            1.283        1.143       
Ação B     0.91            1.818        0.500       
Ação C     1.33            1.485        0.898       
Título D   0.77            0.103        7.462       
Fundo E    1.12            0.177        6.303       


### b) Análise de correlação usando produto interno
- Normalizar os retornos (centrar na média)
    - retornos_centrados = retornos - retornos_medios

- Exercício: Calcular a matriz de correlação usando produto interno
    - $ C_{ij} = <v_i, v_j> / (||v_i||\cdot ||v_j||)$

In [14]:
# b) Análise de correlação usando produto interno
retornos_centrados = retornos - retornos_medios
#a linha de cima tira a media de cada elemento da matriz

print("Matriz de retornos centrados:")
print(retornos_centrados)

# Calcular a matriz de correlação usando produto interno
num_ativos = retornos_centrados.shape[1] # pega a quantidade de ativos que sera usado
matriz_correlacao = np.zeros((num_ativos, num_ativos)) #cria uma  matriz da dimensao num_ativos com zeros

#os for aninhados mostram que eu farei o calculo de  cada elemento da matriz fazendo linha por coluna ,se pa
for i in range(num_ativos):
    for j in range(num_ativos):
        v_i = retornos_centrados[:, i]
        v_j = retornos_centrados[:, j]

        # Calcular o produto interno
        produto_interno = np.dot(v_i, v_j)

        # Calcular as normas (magnitudes)
        norma_v_i = np.linalg.norm(v_i)
        norma_v_j = np.linalg.norm(v_j)

        # Calcular a correlação
        if norma_v_i != 0 and norma_v_j != 0:
            matriz_correlacao[i, j] = produto_interno / (norma_v_i * norma_v_j)
        else:
            matriz_correlacao[i, j] = 0 # Evita divisão por zero se um dos vetores for zero

print("\nMatriz de Correlação:")
print(matriz_correlacao)
#diagonal é sempre 1
#note q é simétrica e poderia fazer apenas para um lado da diagonal e dps copiar
#essa correlação mostra que os "ativos" são semelhantes perante esses argumentos, se uma cresce a outra tb (talvez) cresce se tiverem corr parecidas
#mas corr não implica uma causalidade

Matriz de retornos centrados:
[[ 0.63333333 -2.40833333  1.86666667  0.03333333  0.08333333]
 [ 0.33333333  1.39166667 -1.83333333  0.13333333 -0.01666667]
 [-1.96666667  0.89166667  0.76666667 -0.06666667 -0.21666667]
 [ 1.73333333 -3.00833333  0.46666667  0.03333333  0.18333333]
 [-0.56666667  2.59166667 -2.53333333 -0.16666667 -0.11666667]
 [ 1.03333333 -0.10833333  1.46666667  0.13333333  0.28333333]
 [-2.66666667  1.99166667 -0.83333333 -0.06666667 -0.31666667]
 [ 0.13333333 -1.70833333  1.76666667  0.03333333  0.08333333]
 [ 1.33333333  0.59166667 -2.13333333 -0.16666667 -0.01666667]
 [-1.16666667  1.79166667  0.56666667  0.13333333  0.18333333]
 [ 0.43333333 -2.20833333  1.06666667 -0.06666667 -0.21666667]
 [ 0.73333333  0.19166667 -0.63333333  0.03333333  0.08333333]]

Matriz de Correlação:
[[ 1.         -0.61661665  0.07756007  0.18116709  0.63646006]
 [-0.61661665  1.         -0.67592713 -0.1769571  -0.32639199]
 [ 0.07756007 -0.67592713  1.          0.46623199  0.34324012]
 

In [19]:
# c) Análise de portfolios
print(f"\nc) Análise de diferentes portfolios:")

# Portfolio 1: Igualmente distribuído
pesos1 = np.array([0.2, 0.2, 0.2, 0.2, 0.2])

# Portfolio 2: Conservador (mais em títulos)
pesos2 = np.array([0.1, 0.1, 0.1, 0.5, 0.2])

# Portfolio 3: Agressivo (mais em ações)
pesos3 = np.array([0.4, 0.3, 0.3, 0.0, 0.0])

portfolios = [pesos1, pesos2, pesos3]
nomes_portfolios = ['Equilibrado', 'Conservador', 'Agressivo']

print(f"{'Portfolio':<12} {'Retorno':<10} {'Risco':<10} {'Sharpe':<10}")

for i, (nome, pesos) in enumerate(zip(nomes_portfolios, portfolios)):
    pass
    # Retorno esperado do portfolio
    retorno_medio_portifolio = np.dot(retornos_medios,pesos)
    # Risco do portfolio (norma dos retornos ponderados centrados)
    retornos_ponderado = np.dot(retornos,pesos)
    risco_portfolio = np.std(retornos_ponderado)

    # Sharpe ratio
    shape_portifolio = retorno_medio_portifolio/risco_portfolio
    print(f"{nome:<12} {retorno_medio_portifolio:<10.2f} {risco_portfolio:<10.3f} {shape_portifolio:<10.3f}")


c) Análise de diferentes portfolios:
Portfolio    Retorno    Risco      Sharpe    
Equilibrado  1.12       0.235      4.767     
Conservador  0.98       0.164      5.950     
Agressivo    1.26       0.348      3.617     


# Problema 2: Sistema de busca simples

## Dados:
- Lista de documentos ou páginas
- texto de busca

In [6]:
# Leitura dos arquivos de texto
print("\nLeitura de arquivos de texto:")
doc_dir = "documentos"
arquivos = glob.glob(f"{doc_dir}/*.txt")
docs = []
file_names = [arquivo.split('/')[-1].replace('.txt', '') for arquivo in arquivos]
for arquivo in arquivos:
    with open(arquivo, 'r', encoding='utf-8') as f:
        docs.append(f.read())

# Exemplo de arquivos lidos
print(f"Arquivos encontrados: {len(docs)}")
print("Primeiro arquivo lido:")
print(docs[0][:100] + "...")  # Exibe os primeiros 100 caracteres do primeiro arquivo


Leitura de arquivos de texto:
Arquivos encontrados: 0
Primeiro arquivo lido:


IndexError: list index out of range

In [ ]:
# criação do vetor de características
stopwords_pt = ['a', 'o', 'e', 'de', 'do', 'da', 'em', 'um', 'para', 'com', 'não', 'uma', 'os', 'no', 'se', 'na', 'por', 'mais', 'as', 'dos', 'como', 'mas', 'foi', 'ao', 'ele', 'das', 'tem', 'à', 'seu', 'sua', 'ou', 'ser', 'quando', 'muito', 'há', 'nos', 'já', 'está', 'eu', 'também', 'só', 'pelo', 'pela', 'até', 'isso', 'ela', 'entre', 'era', 'depois', 'sem', 'mesmo', 'aos', 'ter', 'seus', 'quem', 'nas', 'me', 'esse', 'eles', 'estão', 'você', 'tinha', 'foram', 'essa', 'num', 'nem', 'suas', 'meu', 'às', 'minha', 'têm', 'numa', 'pelos', 'elas', 'havia', 'seja', 'qual', 'será', 'nós', 'tenho', 'lhe', 'deles', 'essas', 'esses', 'pelas', 'este', 'dele', 'tu', 'te', 'vocês', 'vos', 'lhes', 'meus', 'minhas', 'teu', 'tua', 'teus', 'tuas', 'nosso', 'nossa', 'nossos', 'nossas', 'dela', 'delas', 'esta', 'estes', 'estas', 'aquele', 'aquela', 'aqueles', 'aquelas', 'isto', 'aquilo', 'estou', 'está', 'estamos', 'estão', 'estive', 'esteve', 'estivemos', 'estiveram', 'estava', 'estávamos', 'estavam', 'estivera', 'estivéramos', 'esteja', 'estejamos', 'estejam', 'estivesse', 'estivéssemos', 'estivessem', 'estiver', 'estivermos', 'estiverem', 'hei', 'há', 'havemos', 'hão', 'houve', 'houvemos', 'houveram', 'houvera', 'houvéramos', 'haja', 'hajamos', 'hajam', 'houvesse', 'houvéssemos', 'houvessem', 'houver', 'houvermos', 'houverem', 'houverei', 'houverá', 'houveremos', 'houverão', 'houveria', 'houveríamos', 'houveriam', 'sou', 'somos', 'são', 'era', 'éramos', 'eram', 'fui', 'foi', 'fomos', 'foram', 'fora', 'fôramos', 'seja', 'sejamos', 'sejam', 'fosse', 'fôssemos', 'fossem', 'for', 'formos', 'forem', 'serei', 'será', 'seremos', 'serão', 'seria', 'seríamos', 'seriam', 'tenho', 'tem', 'temos', 'tém', 'tinha', 'tínhamos', 'tinham', 'tive', 'teve', 'tivemos', 'tiveram', 'tivera', 'tivéramos', 'tenha', 'tenhamos', 'tenham', 'tivesse', 'tivéssemos', 'tivessem', 'tiver', 'tivermos', 'tiverem', 'terei', 'terá', 'teremos', 'terão', 'teria', 'teríamos', 'teriam']
vectorizer = CountVectorizer(stop_words=stopwords_pt)
X = vectorizer.fit_transform(docs)

# Exibe o tamanho da matriz de características
print(f"\nMatriz de características (documentos x termos): {X.shape}")
print("Termos encontrados:")
print(vectorizer.get_feature_names_out()[:20])  # Exibe os primeiros 20 termos

In [7]:
# exemplo de busca: Buscar documento com maior semelhança de coseno
print("\nExemplo de busca: Buscar documento com maior semelhança de coseno")
texto_busca = "comida mais popular no Brasil"
X_busca = vectorizer.transform([texto_busca])

similaridades = cosine_similarity(X_busca, X)
indice_mais_similar = np.argmax(similaridades)

print(f"Documento mais similar encontrado: {file_names[indice_mais_similar]}")
print(f"Conteúdo do documento mais similar:\n{docs[indice_mais_similar][:200]}...")  # Exibe os primeiros 200 caracteres



Exemplo de busca: Buscar documento com maior semelhança de coseno


NameError: name 'vectorizer' is not defined

In [ ]:
# Exercicio: mude o critério de busca para encontrar documentos que estejam mais proximos pela distancia euclidiana